### ISSUE TITLE
Verzicht auf Nachladen von externen Quellen

### ISSUE THREAD

**Issue by adlerweb** [FreifunkMYK/PW-Freifunk-Starter#11]
Aktuell werden bei Aufruf der Webseite automatisch Programmquellen von ausländischen Anbietern nachgeladen - finde ich weder ideologisch noch sicherheitstechnisch sonderlich ansprechend. Ich würde externe Quellen wenn möglich vermeiden wollen (warum muss eine Schriftart "von draußen" kommen?) und - wenn nötig - erst nach Benutzerinteraktion nachladen (Stichwort 2-Klick-Buttons). 

/templates/scripts/_main.inc:18
/templates/_main.inc:19

**Comment by kreativmonkey** [comment]
Es handelt sich bei den Elementen um das aktuelle Iconset Font Awesome sowie Foundation Zurb. Zweiteres habe ich aus dem Code entfernt da es nicht zum Einsatz kommt. Es besteht die Möglichkeit Font Awesome in das Projekt mit auf zu nehmen, jedoch ist das Laden über einen cdn performancetechnisch besser.

Das laden nach Benutzerinteraktion ist hier nicht möglich da es wesentliche Styleelemente betrifft und nicht zur Interaktion mit dem Nutzer geladen werden.

**Comment by adlerweb** [comment]
Ich denke um die 27 Kilobyte beim Besuch einmalig zu laden kann man auf die vermeindliche Performance verzichten. Das ist im Vergleich zu der Bilderflut nicht mehr wirklich relevant.

**Comment by kreativmonkey** [comment]
von mir aus können wir das auch zentral ausliefern, wenn es dir dabei besser geht. Ansonsten kannst du auch einfach einen cdn zur verfügung stellen, dann laden wir den kram von deinem cdn... wäre auch nicht schlecht. Am besten ist es natürlich lokal und extern zu gleich.

**Comment by kreativmonkey** [comment]
So, habe das ganze im dev branch gefixed. Wird nun durch Sass in das Hauptfile geladen.
