### ISSUE TITLE
Router Question

### ISSUE THREAD

**Issue by kreativmonkey** [FreifunkMYK/PW-Freifunk-Starter#13]
1. Es wäre möglich alle Router die Alfred liefert in der key Datenbank auf zu nehmen und an Hand bestimmter Daten ein matching zum Evtl. Router Betreiber durch zu führen, z.B. Aufgrund der Position oder besser der Kontakt Mail. Beim Einloggen kann der User dann gefragt werden ob es sich um ein von ihm betriebenen Router handelt oder nicht. Solange wird er als anonym gelistet. 
2. Router die seit einer bestimmten Zeit offline sind könnten ja aus der Datenbank gelöscht werden, hierzu würde ich jedoch auch eine Abfrage beim User vorschlagen sobald dieser sich einloggt.

**Comment by adlerweb** [comment]
1. Ich denke über Mailadresse wäre praktisch. Geo finde ich nicht so berauschend - da müsste man schon was dynamisches basteln, sonst hat man in Städten zu viel und aufm Land zu wenig drin. Ist IMO den Aufwand an der Stelle nicht wert.
2. Sofern mit "offline" ALFRED gemeint ist: Mit Nachfrage OK, automatisch würde ich nicht so doll finden (Router im Lager, Mobilrouter, etc).

**Comment by kreativmonkey** [comment]
Danke für das Feetback, beide Punkte sind nur Feature Requests. Ohne Nachfragen sollte Punkt 2 nicht laufen das ist richtig! Freut mich jedoch wenn die Idee an sich gut ankommt.
