### ISSUE TITLE
Firmwarefiles

### ISSUE THREAD

**Issue by kreativmonkey** [FreifunkMYK/PW-Freifunk-Starter#16]
So, ich habe mir nochmals Gedanken zu den Firmwarefiles gemacht. Es wurde angesprochen das eine URL wie "https://www.ffmyk.de/firmware/tl-wr841n-d/v9/factory" oder "https://www.ffmyk.de/firmware/tl-wr841n-d/v9/sysupgrade/nightly" schön wäre. Das sehe ich genauso. Ich bin mir nur immer noch nicht ganz einig wie wir das ganze realisieren. Derzeit liegen die Files einfach in einem Ordner dessen Inhalt aufgelistet wird. Das macht das ganze nicht gerade übersichtlich und auch nicht Einsteigerfreundlich. Mein Problem ist, wie verwalte ich die Firmwarefiles über Processwire? 
### Mehrere Probleme müssen gelöst werden:
1. Soll es eine Firmwareaktualisierungsbenachrichtigung geben, hierzu muss ich wissen welche Firmware auf dem Router Installiert ist und welches die aktuelle Firmware ist.
2. Es soll ein Link immer auf das letzte Build (nightly und stable) führen und das für sysupgrade und factory. 
3. Es gibt mehrere Versionen der unterschiedlichen Router welche unterschiedliche Firmware bekommen, ab und an jedoch die selbe.... 
### Lösungsansätze

Ich benötige Ideen zur Lösung des Problems in Form von Struktur und Logik. 
### Erstes Idee
- Aktuell existiert eine liste von Routern, man könnte nun die Firmware Informationen in den Routerseiten hinterlegen und somit beim aufruf der obigen URLs jeweils nach der passenden Firmware suchen. 
- 2x Datumsfeld, einmal Stable einmal Nightly. Aktualisierung je nach Build.
- Die aktuelle Firmware auf den jeweiligen Nodes können wir durch Alfred erfragen und im jeweiligen Node ablegen. 
- Nightlys werden Ignoriert und bekommen nur eine Info wenn es eine aktuellere Stable gibt.
- Firmwareliste listet alle Firmwaredateien und zeigt einen filter. 
##### Problem
- Auslesen des Ordners mit den Firmwaredateien
- Aktualisierung durch Script
##### Wünschenswert
- Speicherung von Router/Firmware versionen
- Nightly und Stable sind gleich benannt damit nur eine Info pro Routerversion gespeichert werden muss. Hierzu muss die Bennenung der Dateien jedoch einem strickten Schema folgen.

**Comment by adlerweb** [comment]
P1: Kommt ja schon jetzt über die nodes.json rein und sollte entsprechend verfügbar sein
P2: HTTP/302? Sollte doch eigentlich per rewrite mit den ausgelesenen Daten machbar sein
P3: Wenn es die selbe ist gibt es trotzdem eine eigene URL - da ist vom Ansprechen her IMO kein Unterschied.

Die Benennung der Daten würde ich nicht groß ändern - das gibt zu viel Chaos wenn man die lokal speichert. Eventuell versuchen das etwas abzukürzen um unter das Zeichenlimit des TP-Foos zu kommen, die Unterscheidung nightly/stable finde ich für das wiederfinden im lokalen Downloadordner aber wichtig. Die aktuelle Stable ist anderer Release und hat entsprechend eine inkompatible Benennung, die würde bei Neueren wie schon geschrieben jetzt schon im Format der aktuellen Nightly-Syntax rausfallen.

Für das Parsen des Ordners hatte ich dir vor einiger Zeit schon einen passenden Beispielcode gesendet.

**Comment by adlerweb** [comment]
Ist IMO vollständig drin, oder?
