### ISSUE TITLE
Statusseite

### ISSUE THREAD

**Issue by kreativmonkey** [FreifunkMYK/PW-Freifunk-Starter#18]
Heute habe ich mir mal die Seite von FFWW angeschaut. Sie gefällt mir recht gut und eine Sache sollten wir überlegen selbst zu übernehmen. Die **Statusseite**, diese ist hier zu finden:
https://status.freifunk-westerwald.de/

Verwendet wird dazu https://cachethq.io/ , eine OpenSource Anwendung zur anzeige von Status für verschiedene Services. Hier könnte man die Webseite, Jabber, evtl Alfred, die Supernodes... eintragen und jeder ist glücklich wenn er irgendwo sehen kann das irgendwas nicht geht.

**Comment by niyawe** [comment]
Ich bekomme bei status.freifunk-westerwald.de nur die Meldung "Diese Webseite ist nicht mehr verfügbar"

**Comment by adlerweb** [comment]
Ja, hatte ich denen vor einiger Zeit auch schon gesagt. Ich bin weiterhin der Meinung, dass so eine Seite eher Blödsinn ist. Sieht schön aus, aber bringt keinen wirklichen Mehrwert. Wenn schon richtiges Monitoring mit entsprechenden Limits und Benachrichtigungsgruppen, ist aber halt sehr viel Aufwand...
