### ISSUE TITLE
Mail "Account Aktivierung": Typo

### ISSUE THREAD

**Issue by adlerweb** [FreifunkMYK/PW-Freifunk-Starter#26]
Sollte der link nicht anklickbar sein -> Sollte der Link nicht anklickbar sein
(sind die Texte alle nur in der Datenbank?)

**Comment by kreativmonkey** [comment]
Welcher Link? Welcher Text? 

Die meisten der Funktionen ist derzeit unter _function.inc 
Ich überlege jedoch sie nach und nach in Module um zu wandeln um etwas flexibler mit ihnen Arbeiten zu  können. Dann werden die Texte in der Datenbank sein, aktuell sind sie jedoch unter _function.inc

**Comment by adlerweb** [comment]
Fixed 36da232a37b78a0c1ff3ea7e3678ed53a6306db7
