### ISSUE TITLE
Profil-Link defekt

### ISSUE THREAD

**Issue by adlerweb** [FreifunkMYK/PW-Freifunk-Starter#27]
Wenn ich auf der Seite "Statische IPs" bin geht der Link "Profil" auf https://www.ffmyk.de/profile/ - das führt zu einer falschen Ausgabe (Keine Router, Fehlende Angaben). Andere Seiten linken auf https://www.ffmyk.de/profile/<username>.

Vorschlag: https://www.ffmyk.de/profile/ immer auf die Seite des aktuell angemeldeten Users umleiten statt ein leeres Template anzuzeigen

**Comment by kreativmonkey** [comment]
Beides ist gefixt. Sowohl der Link unter Statische IPs als auch die weiterleitung auf das eigene Profil beim Aufruf von https://www.ffmyk.de/profile/ .
