### ISSUE TITLE
Image Upload: Problems depending on file size?

### ISSUE THREAD

**Issue by adlerweb** [FreifunkMYK/PW-Freifunk-Starter#32]
Upload of larger files stops or stalles without completion

2364x1576, jpeg98, 3.6MB -> not working
1182x788, jpeg85, 300KB -> working
2364x1576, jpeg85, 904KB -> working
??, jpeg85, 1.1MB -> not working
??. jpeg85, 900KB -> working

seems to me like there is an unchecked size limit defined at 1MB

**Comment by kreativmonkey** [comment]
Sollte nun funktionieren, war lediglich eine Anpassung am Server!
