### ISSUE TITLE
Blog: Missing <title>

### ISSUE THREAD

**Issue by adlerweb** [FreifunkMYK/PW-Freifunk-Starter#33]
Blog overview and posts do not contain a <title> tag

**Comment by adlerweb** [comment]
...same for /node/…

**Comment by kreativmonkey** [comment]
i don't understand what are you mean!

**Comment by adlerweb** [comment]
https://www.ffmyk.de/blog/
https://www.ffmyk.de/node/
...and all subpages

There is no <title>-Tag inside the <head>, as such no document title. 
https://wiki.selfhtml.org/wiki/HTML/Kopfdaten/title
