### ISSUE TITLE
Login mit falschen Kennwort: Fehlermeldung

### ISSUE THREAD

**Issue by adlerweb** [FreifunkMYK/PW-Freifunk-Starter#37]
Bei Login mit inkorrekten Zugangsdaten:

Warning: ldap_bind(): Unable to bind to server: Invalid credentials in /srv/http/freifunk-myk.de/ProcessWire/site/modules/ldapHelper.module on line 124

**Comment by kreativmonkey** [comment]
Ich wüsste nicht wie ich diese Meldung beseitigen könnte! 
Die Ausgabe kommt auch nur solange der Debug Mode aktiviert ist. Zeile 124 versucht ein bind und  bekommt dabei true oder false zurück:

``` php
if(ldap_bind($con, $user_dn, $password)){
```

somit wird das problem schon abgefangen.

**Comment by adlerweb** [comment]
Wenn es abgefangen wird

if(@ldap_bind(... 

## 

Mit freundlichen Grüßen  ||  Sincerely yours
Florian Knodt - www.adlerweb.info -  @adlerweb
