### ISSUE TITLE
Layover "Anmeldung" hat mehrere Issues

### ISSUE THREAD

**Issue by rfelten** [FreifunkMYK/PW-Freifunk-Starter#4]
Mit Firefox 43.0:
- Anmelde Box ist nicht klickbar (Fokus kann nicht gesetzt werden) 
- Keine Nachricht bei fehlerhaften Login

**Comment by kreativmonkey** [comment]
# Fix the Bug

### Anmelde Box nicht klickbar

Es fehlete ein `aria-autoclose="false"` um den Container offen zu halten beim anklicken.

### Nachricht bei fehlerhaften Login

Diese war schon vorbereitet wurde nur leider nicht ausgegeben. Dies habe ich nun zwischen die Navigation und den Text platziert.
