### ISSUE TITLE
Register: PPA

### ISSUE THREAD

**Issue by adlerweb** [FreifunkMYK/PW-Freifunk-Starter#45]
Bei der Registrierung sollte der Nutzer das Pico Peering Agreement akzeptieren:
http://www.picopeer.net/PPA-en.shtml

**Comment by kreativmonkey** [comment]
Besprechung auf dem nächsten Treffen.

**Comment by adlerweb** [comment]
http://map.freifunk-myk.de/#!v:m;n:10feede5f394
-> Franz Peter Straße

https://www.freifunk-myk.de/node/10-fe-ed-e5-f3-94/
-> Paar Meter weiter in anderer Straße

**Comment by adlerweb** [comment]
RFC: Im Setup-Mode zeigen - siehe Tech-ML
