### ISSUE TITLE
Anmeldung: "Passwort vergessen" hat keine Funktion

### ISSUE THREAD

**Issue by rfelten** [FreifunkMYK/PW-Freifunk-Starter#5]
Muss noch implementiert werden :)

**Comment by kreativmonkey** [comment]
So, Passwort vergessen aktueller Status:
- [x] Passwort Vergessen Link
- [x] E-Mail mit Link zusenden
- [x] Neues Passwort eingeben
- [x] Mit neuem Passwort einloggen

**Comment by adlerweb** [comment]
Link noch immer ohne Funktion

**Comment by kreativmonkey** [comment]
Mit Commit 84b96f27c32086e77f5375fe5dfc5ca0d17016f5 geschlossen
