### ISSUE TITLE
Fehlende Eingabevalidierung bei MAC-Adressen?

### ISSUE THREAD

**Issue by adlerweb** [FreifunkMYK/PW-Freifunk-Starter#51]
Aktuell ist in der Nodekey-API, welche von den fastds gelesen wird, eine MAC-Adresse mit Newline-Zeichen am Ende. Hierdurch wird an den Supernodes eine Formatwarnung ausgegeben.

Vermutung: Die MAC-Adresse wird nur bei der Eingabe aber nicht bei der Speicherung validiert - wenn man über den Link im Setup-Mode auf die Seite gelangt scheint der Fehler nicht abgefangen zu werden.
Empfehlung: trim(); strtoupper; preg_match('/^[0-9A-F]{2}[:]){5}([0-9A-F]{2}$/')

**Comment by kreativmonkey** [comment]
Eingabevalidierung funktioniert so halbwegs.....

**Comment by kreativmonkey** [comment]
Das hat sich schon erledigt! Die MAC Adressen werden nun Validiert und Standatisiert! Siehe Commit [c8f699fb](https://github.com/FreifunkMYK/PW-Freifunk-Starter/commit/c8f699fb982339600849857c5b67c578876e59ea)
