### ISSUE TITLE
Webseite: HowTo nicht erreichbar

### ISSUE THREAD

**Issue by adlerweb** [FreifunkMYK/PW-Freifunk-Starter#52]
https://twitter.com/altherr/status/768221287122608129

> @FreifunkMYK Auf https://www.freifunk-myk.de  ist der "HowTo"-Link kaputt, der vermutlich für alle potentiellen Interessenten der wichtigste ist

**Comment by kreativmonkey** [comment]
Vorrübergehend gefixt.
