### ISSUE TITLE
Knotendetails: Standort falsch

### ISSUE THREAD

**Issue by adlerweb** [FreifunkMYK/PW-Freifunk-Starter#53]
In der Detailansicht der Webseite wird der Knoten sowohl auf der Embedded-Karte als auch der Straßenbeschreibung ca. 500m neben dem im Router angegebenen Standort dargestellt

**Comment by kreativmonkey** [comment]
Ich bitte um mehr Informationen, um welchen Knoten handelt es sich und auf welchem Link? Ich habe am Code nichts geändert und bei den Routern die ich überprüft hatte stimmte es.

**Comment by adlerweb** [comment]
http://map.freifunk-myk.de/#!v:m;n:10feede5f394
-> Franz Peter Straße

https://www.freifunk-myk.de/node/10-fe-ed-e5-f3-94/
-> Paar Meter weiter in anderer Straße

**Comment by kreativmonkey** [comment]
Ja, ich sehe es gerade, ich verstehe nur nicht was das Problem ist, die Daten der Nodes haben sich nicht geändert und ich habe am Code auch nichts geändert und vor ein paar Tagen ging es ja noch!

**Comment by kreativmonkey** [comment]
irgendwie hatta das feld nur noch zwei stellen nach dem komma gespeichert obwohl es ein float feld war... ich habe das ganze nochmal aktualisiert und nun gehts!
