### ISSUE TITLE
Knotenregistrierung: Login geht auf Startseite

### ISSUE THREAD

**Issue by adlerweb** [FreifunkMYK/PW-Freifunk-Starter#54]
Aktuell:
- Nicht angemeldet
- Auf "Knoten Registrieren"-Link klicken
- Oben auf Login und Zugangsdaten eingeben
- Man kommt auf die Startseite
- Nochmaliges Aufrufen des Originallinks führt zum Add-Node-Formular

im vorletzten Schritt sollte man besser direkt auf die Seite geleitet werden, welche vor dem Login versucht wurde aufzurufen - in diesem Fall also das vorausgefüllte Add-Node-Formular

**Comment by kreativmonkey** [comment]
Ich verstehe nicht wieso du auf die Startseite kommst, ich bleibe auf der Node Add seite!

Browser: Firefox
URL: https://www.freifunk-myk.de/node/add/

Benachrichtigung

> Gesicherte Seite
> Bitte Anmelden oder Registrieren

Dann melde ich mich an und das Formular zum eingeben erscheint.

**Comment by kreativmonkey** [comment]
Gefixt mit Commit [c8f699fb9](https://github.com/FreifunkMYK/PW-Freifunk-Starter/commit/c8f699fb982339600849857c5b67c578876e59ea)
