### ISSUE TITLE
Umleitung maps.freifunk-myk.de

### ISSUE THREAD

**Issue by adlerweb** [FreifunkMYK/PW-Freifunk-Starter#55]
Aktuell zeigt maps… auf calyrium.org - sollte man für die Google-Nutzer auf map… weiterleiten

**Comment by niyawe** [comment]
Habe mal meine nginx-config angepasst. Du kannst also auch nen CNAME auf den map-server machen.

**Comment by kreativmonkey** [comment]
Der CNAME eintrag lag schon auf map.ffmyk.niyawe.de.

**Comment by adlerweb** [comment]
Kann ich nicht bestätigen...

`$ wget -O - http://maps.freifunk-myk.de
--2016-09-07 16:00:43--  http://maps.freifunk-myk.de/
Auflösen des Hostnamens »maps.freifunk-myk.de (maps.freifunk-myk.de)« 5.9.39.68
Verbindungsaufbau zu maps.freifunk-myk.de (maps.freifunk-myk.de) 5.9.39.68:80 verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet 301 Moved Permanently
Platz: https://calyrium.org/ [folgend]
--2016-09-07 16:00:43--  https://calyrium.org/
...`

**Comment by kreativmonkey** [comment]
ich sehe soeben das du **maps**.freifunk-myk.de haben willst. Bisher ist nur **map**.freifunk-myk.de auf die Karte geleitet. Gerne richte ich es auch noch für maps ein ;)
