### ISSUE TITLE
Doppelte MAC in der API

### ISSUE THREAD

**Issue by kreativmonkey** [FreifunkMYK/PW-Freifunk-Starter#78]
Die MAC Adresse C0:4A:00:4A:03:4E ist doppelt in der API abfrageliste der Node Keys. Das kommt daher das der Node nun in der neuen Liste eingetragen wurde und in der Alten liste auch vorhanden ist:

```php
$router_new = $pages->find("template=node, key!=''")->explode(function($item) {
                          return array(
                            'MAC' => $item->title,
                            'PublicKey' => strtoupper($item->key)
                          );
                        });
          // get and merge the old and new keylist
          $router_old = file_get_contents("http://register.freifunk-myk.de/srvapi.php");
          $router_old = unserialize($router_old);
          $list = array_merge($router_old, $router_new);
```

Ich schätze er filtert den Node nicht raus da er einen neuen Key erhalten hat und daher der alte und der neue Node durch array_merge nicht raus gefiltert. Hier bedarf es Code anpassungen so das nur noch die MAC Adresse dazu führt das der alte router nicht mehr in der liste auftaucht!

Ideen sind willkommen ;-)

**Comment by adlerweb** [comment]
Kann ich nicht viel zu sagen - dieses nesting des CMS kenne ich nicht. Könnte höchstens hintendran mehrere Läufe zum mergen machen, also sowas in der Art…

```php
$router_new = $pages->find("template=node, key!=''")->explode(function($item) {
                          return array(
                            'MAC' => $item->title,
                            'PublicKey' => strtoupper($item->key)
                          );
                        });
          // get and merge the old and new keylist
          $router_old = file_get_contents("http://register.freifunk-myk.de/srvapi.php");
          $router_old = unserialize($router_old);

$list = array();
$doneMac = array();
foreach($router_new as $r) {
    $list[] = $r;
    $doneMac[] = $r['MAC'];
}
foreach($router_old as $r) {
    if(in_array($r['MAC'], $doneMac)) continue;
    $list[] = $r;
}
```

**Comment by kreativmonkey** [comment]
Also der code oben ist, bis auf die erzeugung des arrays aus der neuen Datenbank, reines PHP und hat absolut nichts mit dem verwendeten Framework zu tun! Ich erzeuge ein Array aus MAC und PublicKey so wie es auch in der alten Datenbank der fall war, die serialisieten daten der alten API werden abgerufen und mit dem neuen array gemerged und dann serialisiert um die liste an die supernodes weiter zu reichen. 

$item ist das objekt der nodes und title enthält die mac und key den key.
