### ISSUE TITLE
Freifunk Rheinland Spendenseite

### ISSUE THREAD

**Issue by niyawe** [FreifunkMYK/PW-Freifunk-Starter#81]
Freifunk Rheinland hätte gerne als Gegenleistung für den Transit durch den Rheinland Backbone die Spendenseite (https://www.freifunk-rheinland.net/mitmachen/spenden/) auf unserer Website verlinkt.

**Comment by kreativmonkey** [comment]
Gibt es eine etwas genauer Vorgabe wie das ganze verlinkt sein soll? Ein Link auf der Startseite oder auch auf den Unterseiten? Langt ein verweis wie "Unterstützt durch Freifunk Rheinland e.V." im Footer oder an anderer Stelle? Oder soll ein direkter Aufruf zur Spende gestartet werden?

**Comment by adlerweb** [comment]
Üblich ist eine Erwähnung im Bereich "Mitmachen" oder eine eigene Spenden-Seite. Da wir selbst keine Spenden annehmen können und FFRL gemeinnützig ist sollten wir da IMO ruhig prominent für Werben ;)

**Comment by kreativmonkey** [comment]
So, ein Spendenaufruf steht auf der Startseite. Nun fehlt noch ein Blogartikel zum Thema das wir zu Freifunk-Rheinland umgestellt haben! Ist schließlich eine wichtige Information!!!

**Comment by Confectrician** [comment]
Da das nun eh bei den "berühmten" Platzhalter-Bildern ist, 
würde sich da nicht auch ein Freifunk Rheinland Logo anbieten?

z.B.:
https://github.com/grmpy/ffrl-ci/blob/master/Logo/ffrhein_logo_claim_line.pdf

**Comment by kreativmonkey** [comment]
War auch meine Überlegung! Ist halt nen absolut beschissenes Format das Logo von denen!!!

**Comment by kreativmonkey** [comment]
Ist erledigt!

**Comment by Confectrician** [comment]
Schaut doch gut aus.
