### ISSUE TITLE
Knoten ohne Namen lassen sich nicht löschen/editieren

### ISSUE THREAD

**Issue by adlerweb** [FreifunkMYK/PW-Freifunk-Starter#85]
Da der Link zum Bearbeiten/Löschen auf den Namen gesetzt ist lassen sich Knoten ohne Namen nicht löschen/editieren.

![nodedel](https://user-images.githubusercontent.com/1146482/36995786-52b739ac-20b5-11e8-9bde-ddea4949b914.png)

**Comment by kreativmonkey** [comment]
Fixe ich noch, notfalls kannst du die URL mit der MAC aufrufen anstelle vom : bitte ein - und alles in Kleinbuchstaben.

**Comment by adlerweb** [comment]
Hatte ich versucht - da kam HTTP/500

**Comment by Confectrician** [comment]
>notfalls kannst du die URL mit der MAC aufrufen

Vielleicht dann direkt die Verlinkung auf die MAC setzen?
Ich behaupte jetzt mal ganz kühn, dass in der Regel eine MAC vorhanden sein wird im Gegensatz zum Namen.

**Comment by kreativmonkey** [comment]
Es lassen sich derzeit gar keine Nodes löschen. Irgendwie bekomme ich ein memory size error, weiß aber noch nicht so genau wieso. ``Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 83890176 bytes) (line 493 of /srv/http/freifunk-myk.de/ProcessWireDev/site/assets/cache/FileCompiler/site/templates/_function.inc)``
