### ISSUE TITLE
Datenschutzerklärung überarbeiten?

### ISSUE THREAD

**Issue by kreativmonkey** [FreifunkMYK/PW-Freifunk-Starter#86]
**Idiot!!!!!**

**Comment by kreativmonkey** [comment]
26.05.2018

**Comment by Confectrician** [comment]
Ich fand/finde diesen Blog bisher recht hilfreich.
Da aktuell eben zur DSGVO ein Artikel rauskam, dokumentiere ich den hier mal.

https://binary-butterfly.de/artikel/dsgvo-so-viel-panik-fuer-nichts-neues-und-warum-es-trotzdem-ein-grundlegendes-problem-gibt/

**Comment by Confectrician** [comment]
Daraus abgeleitet mal eine Checkliste, was wir denn theoretisch machen müssten.
(Gerne ergänzen/korriegieren bei Bedarf.)

- [x] Verschlüsselung anbieten
- [x] Auftrag zur Datenverarbeitung
Nutzen wir denn überhaupt irgendwelche Tracking Tools, denen wir Daten übergeben oder machen wir das wenn alles selbst?
- [x] Sinnvolle Cookie Nutzung
- [x] ...

Ich gehe aktuell davon aus, dass wir schon sehr minimalistisch unterwegs sind und auch wenig bis keine Daten an Drittanbieter gehen.

**Comment by kreativmonkey** [comment]
## Daten an Drittanbieter

Als Drittanbieter könnten wir evtl. Freifunk.net und Freifunk-Rheinland e.V. ansehen. an Freifunk.net gehen jedoch lediglich statistische Daten (Anzahl der Nodes, SSID und solche Dinge) und über Freifunk-Rheinland geht der Netzverkehr ins Internet. Beides jedoch mehr als ausreichend Anonymisiert.

Alle Webdienste (außer Twitter, Github und die Mailingliste) sind selbst gehostet und haben als Drittanbieter somit lediglich den Hostingprovider / das Rechenzentrum. Wenn ich jetzt drüber nachdenke, wie weit reicht denn der weg des "Drittanbeiters"? Müssen wir also vor und hinter der Haustüre kehren, sprich auch darauf hinweisen die Daten der Kunden auch an/über ihren Provider fließen?

Zum Punkt Tracking-Tools, es gibt lediglich das Log-File vom Webserver zum Debugging. Ansonsten war gewünscht keinerlei Tracking auf der Webseite ein zu setzen. (Ich hätte zwar gerne ein paar Daten über die Zugriffsdaten, das würde wenn aber auch nur über eine selbstgehostete Lösung laufen. )

## Cookie
Sinnvolle Cookie Nutzung ist für mich etwas unverständlich.... ein Cookie ist für das Session Handling zuständig, genau dafür wird er auch verwendet....

**Comment by adlerweb** [comment]
- Wir sollten ggf. noch darauf hinweisen, dass die Daten des Routers (MAC/Name/Kontaktdaten) öffentlich sind und von Dritten (z.B. freifunk-karte.de) genutzt werden. Gehört aber IMO eher in die Firmware.
- In der Wiki wird als Drittanbieter bootstrapcdn.com genutzt.
- In der Wiki (evtl auch Blog?) sind teilweise externe Inhalte von vimeo und youtube drin, da wäre ein Click-to-Play o.Ä. hilfreich, sodass die Nutzerdaten nicht direkt weitergegeben werden.
- Log-File vom Webserver sollte möglichst ausgeschaltet/anonymisiert werden, sofern kein aktives Debugging stattfindet.

**Comment by kreativmonkey** [comment]
Da das Editieren gerade nicht möglich ist, hier noch ein Link zu einem Modul das wir nutzen können:

https://modules.processwire.com/modules/markup-cookie-consent/

damit hätten wir zumindest die Schuldigkeit bei den Cookies getan. Dazu müssen wir jedoch Processwire aktualisieren oder das Modul umschreiben ;).

**Comment by kreativmonkey** [comment]
Das Logging möchte ich ungerne ausschalten zumal es bei meinem aktuellen Setup mehrere Stellen betrifft. Jedoch habe ich das hier (gefunden)[https://stackoverflow.com/questions/6477239/anonymize-ip-logging-in-nginx]:

´´´
map $remote_addr $ip_anonym1 {
 default 0.0.0;
 "~(?P<ip>(\d+)\.(\d+)\.(\d+))\.\d+" $ip;
 "~(?P<ip>[^:]+:[^:]+):" $ip;
}

map $remote_addr $ip_anonym2 {
 default .0;
 "~(?P<ip>(\d+)\.(\d+)\.(\d+))\.\d+" .0;
 "~(?P<ip>[^:]+:[^:]+):" ::;
}

map $ip_anonym1$ip_anonym2 $ip_anonymized {
 default 0.0.0.0;
 "~(?P<ip>.*)" $ip;
}

log_format anonymized '$ip_anonymized - $remote_user [$time_local] ' 
   '"$request" $status $body_bytes_sent ' 
   '"$http_referer" "$http_user_agent"';

access_log /var/log/nginx/access.log anonymized;
´´´

Umsetzung werde ich mir dann mal anschauen. Eigentlich interessiert mich meist nur was angefragt wurde und welcher Fehler auftritt... Zum Bannen müsste man jedoch wieder die IP mit loggen... das doch alles scheiße!!! 

Was ist eigentlich mit dem DNS Provider? Loggen die evtl.? Irgendwie ist das nen Ding mit endlosem Rattenschwanz!!

**Comment by adlerweb** [comment]
>Was ist eigentlich mit dem DNS Provider

Wir verweisen die Besucher nicht aktiv auf den, von daher dürften wir da sauber sein

> Irgendwie ist das nen Ding mit endlosem Rattenschwanz!

Dann setz das erst mal in einer "richtigen" IT-Installation um ;)

**Comment by kreativmonkey** [comment]
Der Artikel von @Confectrician ist aber sehr interessant und zeigt eigentlich das wir über 90% schon umsetzen. Hauptsächlich geht es hier nämlich um Drittanbieter und Datensparsamkeit, was ja schon länger gilt. Interessant ist der Part mit dem Datenschutzbeauftragten, ich hoffe so was gilt wirklich nur für Firmen und nicht auch für lose Gruppierungen.

**Comment by kreativmonkey** [comment]
Noch ein Artikel der ganz hilfreich ist. Hier steht auch was von einem "Verzeichnis der Verarbeitungstätigkeit". https://www.impulse.de/recht-steuern/rechtsratgeber/dsgvo-checkliste/7297857.html

**Comment by Confectrician** [comment]
>Sinnvolle Cookie Nutzung ist für mich etwas unverständlich....

Das war auch bezogen auf den Artikel-Inhalt.
Da ging es um sinnvoll genutzet Cookies wie für den Login und andere wie z.b. fürs Tracking.
Ich bin mir ziemlich sicher, dass wir wahrscheinlich schon sehr minimalistisch unterwegs sein werden.
