### ISSUE TITLE
Login auf Blogseiten funktioniert nicht

### ISSUE THREAD

**Issue by kreativmonkey** [FreifunkMYK/PW-Freifunk-Starter#89]
Es ist nicht möglich sich ein zu loggen wenn man sich auf dem Blog befindet.

**Comment by kreativmonkey** [comment]
Also, ich konnte den Fehler dahingehend eingrenzen das das Anmeldeformular in einem Blogpost nicht abgeschickt wird. Leider konnte ich aber noch nicht herausfinden wieso das der Fall ist.

```php
<?php if(!wire('user')->isLoggedin()){ ?>
<div id="signin" class="f-dropdown small content" data-dropdown-content aria-autoclose="false">
    <form id="formLogin" action='./' method='post'>
      <div >
        <input name="username" id="username" placeholder="Benutzername" type="text" />
        <input name="password" id="password" placeholder="Passwort" type="password" />
      </div>
      <div >
        <button type="submit" id="btnLogin" name='submit' value='Login' class="btn btn-default">Login</button>
        <button type="submit" id="btnRegister" formaction="<?php echo $pages->get("/registration/")->httpUrl; ?>" class="btn btn-default">Registrieren</button>
      </div>
    </form>
    <a href="<?=$pages->get("template=passwordreset")->url?>">Password vergessen?</a>
</div>
<?php } ?>
```

Ich habe über ein debugging die post inputs ausgewertet und sobald ich auf einem Blogartikel bin kommen keine rein wenn ich das Formular absende. Im Moment habe ich keinen Plan woran es liegt. 

Der Login funktioniert sonst auf allen Seiten!

**Comment by adlerweb** [comment]
Es funktioniert auch auf anderen Sub-Seiten nicht, z.B. in Router-Details. 
How about
`<form id="formLogin" action='/' method='post'>`

**Comment by adlerweb** [comment]
POST-Request auf anderen Seiten:
`username=adlerweb&password=12345&submit=Login`
POST-Request über Blog:
`user=adlerweb&pass=12345&submit=Login`

username <-> user

Blog hat auch entsprechendes Form
`<input name="user" id="user" placeholder="Benutzername" type="text">`
scheint also nicht von dem von dir geposteten Code zu kommen

**Comment by kreativmonkey** [comment]
..... vorher hieß es überall user, ich habe es beim testen auf username und password umgeändert da ich es leserlicher finde! Aber danke für den Hinweis, ich schaue nochmal wie das zustande kommt!

**Comment by kreativmonkey** [comment]
HAHAHA ok, ich habe den Fehler entdeckt!!! Die Blogseiten werden gecached, daher steht dort auch immer noch name="user"! Das war der entscheidende Hinweis. Ich muss mal schauen ob ich das Caching für den Loginteil übergehen kann oder wie ich es genau anstelle!

**Comment by kreativmonkey** [comment]
Ok, ging einfacher als gedacht. Man kann das Caching über bestimmte GET/POST Requests deaktivieren, somit ist dann auch ein Login möglich!
